// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: query.sql

package db

import (
	"context"
	"database/sql"
)

const createAsset = `-- name: CreateAsset :one
INSERT INTO
    asset (entry_id, "location")
VALUES
    (?, ?) RETURNING id, entry_id, location
`

type CreateAssetParams struct {
	EntryID  sql.NullInt64
	Location sql.NullString
}

func (q *Queries) CreateAsset(ctx context.Context, arg CreateAssetParams) (Asset, error) {
	row := q.db.QueryRowContext(ctx, createAsset, arg.EntryID, arg.Location)
	var i Asset
	err := row.Scan(&i.ID, &i.EntryID, &i.Location)
	return i, err
}

const createEntry = `-- name: CreateEntry :one
INSERT INTO
    entry (name, origin, desc)
VALUES
    (?, ?, ?) RETURNING id, name, origin, "desc"
`

type CreateEntryParams struct {
	Name   string
	Origin string
	Desc   string
}

func (q *Queries) CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error) {
	row := q.db.QueryRowContext(ctx, createEntry, arg.Name, arg.Origin, arg.Desc)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Origin,
		&i.Desc,
	)
	return i, err
}

const getEntries = `-- name: GetEntries :many
SELECT
    entry.id, entry.name, entry.origin, entry."desc",
    a.id, a.entry_id, a.location
FROM
    entry
    JOIN asset a on a.entry_id = entry.id
ORDER BY
    entry.id
`

type GetEntriesRow struct {
	Entry Entry
	Asset Asset
}

func (q *Queries) GetEntries(ctx context.Context) ([]GetEntriesRow, error) {
	rows, err := q.db.QueryContext(ctx, getEntries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEntriesRow
	for rows.Next() {
		var i GetEntriesRow
		if err := rows.Scan(
			&i.Entry.ID,
			&i.Entry.Name,
			&i.Entry.Origin,
			&i.Entry.Desc,
			&i.Asset.ID,
			&i.Asset.EntryID,
			&i.Asset.Location,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEntry = `-- name: GetEntry :one
SELECT
    entry.id, entry.name, entry.origin, entry."desc"
FROM
    entry
WHERE
    id = ?
LIMIT
    1
`

type GetEntryRow struct {
	Entry Entry
}

func (q *Queries) GetEntry(ctx context.Context, id int64) (GetEntryRow, error) {
	row := q.db.QueryRowContext(ctx, getEntry, id)
	var i GetEntryRow
	err := row.Scan(
		&i.Entry.ID,
		&i.Entry.Name,
		&i.Entry.Origin,
		&i.Entry.Desc,
	)
	return i, err
}
